config/routes.rb
Rails.application.routes.draw do
  
  root "application#index"

  namespace :api do
    resources :features, only: [:index]
    resources :comments, only: [:create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :data
end

app/models/datum.rb
class Datum < ApplicationRecord
    has_many :comments
end

app/controllers/api/comments_controller.rb
# Description: This controller is responsible for handling the API requests for the comments endpoint.

class Api::CommentsController < ApplicationController
    def create
        feature = Datum.find(params[:external_id])
    
        # Validates boby is not empty
        if params[:body].blank?
            render json: { error: "El cuerpo del comentario no puede estar vacío" }, status: :unprocessable_entity
            return
        end
    
        # Create a new comment for the feature
        comment = feature.comments.build(body: params[:body])
    
        if comment.save
            render json: comment, status: :created
        else
            render json: { error: "No se pudo crear el comentario" }, status: :unprocessable_entity
        end
    end
end

app/controllers/api/features_controller.rb
# Description: This controller is responsible for handling the API requests for the features endpoint.

class Api::FeaturesController < ApplicationController
    
    def index
        # Fetch all the data from the database
        features = Datum.all
    
        # Filter by mag_type if present
        if params[:filters].present? && params[:filters][:mag_type].present?
            features = features.where(mag_type: params[:filters][:mag_type])
        end

        # Paginate the data with a default of 1000 records per page
        per_page = params[:per_page].to_i
        per_page = 1000 if per_page <= 0 || per_page > 1000
        features = features.page(params[:page]).per(per_page)
    
        # Return the paginated data as JSON
        render json: {
            data: features.map { |datum| serialize_feature(datum) },
            pagination: {
                current_page: features.current_page,
                total: features.total_count,
                per_page: per_page
            }
        }
    end
    
    private
    
    # Serialize the data to JSON format for the API response
    def serialize_feature(datum)
        {
            id: datum.id,
            type: "feature",
            attributes: {
                external_id: datum.external_id,
                magnitude: datum.magnitude,
                place: datum.place,
                time: datum.time,
                tsunami: datum.tsunami,
                mag_type: datum.mag_type,
                title: datum.title,
                coordinates: {
                    longitude: datum.longitude,
                    latitude: datum.latitude
                }
            },
            links: {
                external_url: datum.url
            }
        }
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def index
    end
end

app/helpers/api/features_helper.rb
module Api::FeaturesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/index.html.erb
<h1 class="text-3xl font-bold mb-6">Seismology API Viewer 🌍</h1>

<div class="flex  mb-6">
    <form action="<%= api_features_path %>" method="get" id="pageForm">
        <label for="page" class="font-bold">Ir a página:</label>
        <select name="page" id="page">
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
            <option value="5">5</option>
            <option value="6">6</option>
            <option value="7">7</option>
            <option value="8">8</option>
            <option value="9">9</option>
            <option value="10">10</option>
        </select>
    </form>

    <%= link_to "Ver features >>", api_features_path(page: 1), class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-6 mx-4 rounded", id: "viewAllLink" %>

    <script>
    // Function to change the view all link when the page select changes
        document.getElementById('page').addEventListener('change', function() {
            var selectedPage = this.value;
            var viewAllLink = document.getElementById('viewAllLink');
            viewAllLink.href = "<%= api_features_path(page: '') %>" + selectedPage;
        });
    </script>

</div>

<div class="flex">
    <form action="<%= api_features_path %>" method="get" id="magTypeForm">
        <label for="mag_type" class="font-bold">Filtrar por mag_type:</label>
        <select name="filters[mag_type]" id="mag_type">
            <option value="">Todos</option>
            <option value="md">md</option>
            <option value="ml">ml</option>
            <option value="ms">ms</option>
            <option value="mw">mw</option>
            <option value="me">me</option>
            <option value="mi">mi</option>
            <option value="mb">mb</option>
            <option value="mlg">mlg</option>
        </select>
    </form>

    <%= link_to "Filtrar >>", api_features_path(filters: { mag_type: '' }), class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-6 mx-4 rounded", id: "viewFilteredLink" %>

    <script>
        // Function to change the view filtered link when the mag_type select changes
        document.getElementById('mag_type').addEventListener('change', function() {
            var selectedMagType = this.value;
            var viewFilteredLink = document.getElementById('viewFilteredLink');
            viewFilteredLink.href = "<%= api_features_path(filters: { mag_type: '' }) %>" + selectedMagType;
        });
    </script>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Seismology</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-blue-800">
    <main class="flex items-center justify-center">
      <div class="flex flex-col items-center justify-center bg-white p-10 rounded-lg shadow-lg shadow-black min-w-xl max-w-xl mt-24 mb-6 mx-4">
        <%= yield %>
      </div>
    </main>
  </body>
</html>